### ISSUE TITLE
Does HistomicsTK viewer (GeoJS) support annotations with exclusions?

### ISSUE THREAD

**Issue by kavehtp** [DigitalSlideArchive/HistomicsTK#811] opened 2020-01-22 11:03 UTC
Is it possible in GeoJS to display polygons with holes (exclusions)?

The problem is that in many cases, the annotation is a large polygon showing a big part of the tissue but smaller regions inside the annotation should not be filled with the same color. So the idea is to have smaller polygons inside the main polygon to denote exclusions and these exclusions should not be filled with the fill color.

**Comment by manthey** [comment] 2020-01-22 13:36
GeoJS supports drawing (rendering) polygons with holes, but we haven't exposed this in either the polygon creation tool or in the format where polygons are stored in the annotation records used in HistomicsTK.

Closing this issue since it is functionally a duplicate of #675.

**Closed by manthey** 2020-01-22 13:36 UTC
