### ISSUE TITLE
Frontend errors after a successful deployment

### ISSUE THREAD

**Issue by kavehtp** [DigitalSlideArchive/HistomicsTK#654] opened 2019-05-15 11:54 UTC
After deploying Girder and HistomicsTK (using any of the deployment methods), the app displays the following error messages in **Chrome's developer tools console**:

```
Subflow.js:19 Uncaught ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (Subflow.js:19)
    at __webpack_require__ (bootstrap 2807025b36ef0a551a73:19)
    at Object.<anonymous> (plugin.min.js:47633)
    at __webpack_require__ (bootstrap 2807025b36ef0a551a73:19)
    at Object.<anonymous> (plugin.min.js:2899)
    at __webpack_require__ (bootstrap 2807025b36ef0a551a73:19)
    at Object.<anonymous> (loader.js:105)
    at __webpack_require__ (bootstrap 2807025b36ef0a551a73:19)
    at Object.<anonymous> (plugin.min.js:33457)
    at __webpack_require__ (bootstrap 2807025b36ef0a551a73:19)
(anonymous) @ Subflow.js:19
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ plugin.min.js:47633
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ plugin.min.js:2899
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ loader.js:105
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ plugin.min.js:33457
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ JobListWidget.js:122
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ plugin.min.js:30843
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ plugin.min.js:30197
__webpack_require__ @ bootstrap 2807025b36ef0a551a73:19
(anonymous) @ bootstrap 2807025b36ef0a551a73:64
(anonymous) @ bootstrap 2807025b36ef0a551a73:66

JobStatus.js from dll-reference girder_plugin_jobs:1 Uncaught TypeError: __webpack_require__(...) is not a function
    at Object.<anonymous> (JobStatus.js from dll-reference girder_plugin_jobs:1)
    at __webpack_require__ (bootstrap a0dc1054ffe15b29e1b3:19)
    at Object.<anonymous> (JobStatus.js:1)
    at __webpack_require__ (bootstrap a0dc1054ffe15b29e1b3:19)
    at Object.<anonymous> (main.js:4)
    at __webpack_require__ (bootstrap a0dc1054ffe15b29e1b3:19)
    at bootstrap a0dc1054ffe15b29e1b3:64
    at bootstrap a0dc1054ffe15b29e1b3:66
(anonymous) @ JobStatus.js from dll-reference girder_plugin_jobs:1
__webpack_require__ @ bootstrap a0dc1054ffe15b29e1b3:19
(anonymous) @ JobStatus.js:1
__webpack_require__ @ bootstrap a0dc1054ffe15b29e1b3:19
(anonymous) @ main.js:4
__webpack_require__ @ bootstrap a0dc1054ffe15b29e1b3:19
(anonymous) @ bootstrap a0dc1054ffe15b29e1b3:64
(anonymous) @ bootstrap a0dc1054ffe15b29e1b3:66

pluginUtils.js from dll-reference girder_plugin_jobs:1 Uncaught TypeError: __webpack_require__(...) is not a function
    at Object.<anonymous> (pluginUtils.js from dll-reference girder_plugin_jobs:1)
    at __webpack_require__ (bootstrap 0157b9ce2e523b0c7bff:19)
    at Object.<anonymous> (main.js:1)
    at __webpack_require__ (bootstrap 0157b9ce2e523b0c7bff:19)
    at bootstrap 0157b9ce2e523b0c7bff:64
    at bootstrap 0157b9ce2e523b0c7bff:66
(anonymous) @ pluginUtils.js from dll-reference girder_plugin_jobs:1
__webpack_require__ @ bootstrap 0157b9ce2e523b0c7bff:19
(anonymous) @ main.js:1
__webpack_require__ @ bootstrap 0157b9ce2e523b0c7bff:19
(anonymous) @ bootstrap 0157b9ce2e523b0c7bff:64
(anonymous) @ bootstrap 0157b9ce2e523b0c7bff:66

PanelGroup.js from dll-reference girder_plugin_slicer_cli_web:1 Uncaught TypeError: __webpack_require__(...) is not a function
    at Object.<anonymous> (PanelGroup.js from dll-reference girder_plugin_slicer_cli_web:1)
    at __webpack_require__ (bootstrap 6540fc157da07cdaa8ca:19)
    at Object.<anonymous> (ImageView.js:11)
    at Object.<anonymous> (plugin.min.js:2677)
    at __webpack_require__ (bootstrap 6540fc157da07cdaa8ca:19)
    at Object.<anonymous> (routes.js:2)
    at __webpack_require__ (bootstrap 6540fc157da07cdaa8ca:19)
    at Object.<anonymous> (app.js:10)
    at __webpack_require__ (bootstrap 6540fc157da07cdaa8ca:19)
    at Object.<anonymous> (index.js:1)
```

And here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/18053246/57772934-627a2200-7749-11e9-8ce1-bc8c1ca3f962.png)

Clicking on the HistomicsTK link ends up in a blank page with errors as well:

![image](https://user-images.githubusercontent.com/18053246/57773349-69edfb00-774a-11e9-8da7-1c8f8e875de2.png)

This seems to be caused by a change in a dependency package. Any help is greatly appreciated. Thanks!

**Comment by manthey** [comment] 2019-05-15 16:39
This is caused by changes in upstream packages that also affect Girder 2.x-maintenance branch.  See https://github.com/girder/girder/pull/3039 for a potential solution.  Once that (or something similar) gets merged in, HistomicsTK will deploy properly again.

**Comment by manthey** [comment] 2019-05-15 19:05
This should be fixed now that https://github.com/girder/girder/pull/3039 is merged.  Please reopen or create a new issue as needed.

**Closed by manthey** 2019-05-15 19:05 UTC

**Comment by kavehtp** [comment] 2019-05-16 06:41
Thanks David. The problem is resolved.
