### ISSUE TITLE
Multiselect does not work when more than one annotation style is viewed simultaneously

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#540] opened 2018-09-06 17:52 UTC
Specifically, it becomes unreliable when making the right click to invoke the context menu. The problem disappears when only one annotation style (color/alpha/etc) is viewed.

**Comment by jbeezley** [comment] 2018-09-24 14:59
I'm fairly certain this is caused by unexpected behavior related to #534.

**Comment by jbeezley** [comment] 2018-10-04 17:19
Fixed by #550.

**Closed by jbeezley** 2018-10-04 17:19 UTC
Labels: bug
